team_task_manager/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#home'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

  resources :projects do 
    resources :tasks
  end

  post '/projects/:id/complete', to: 'projects#complete', as: 'project_complete'
  post '/tasks/:id/complete', to: 'tasks#complete', as: 'task_complete'

  resources :comments
  get '/users', to: 'users#index'
end

team_task_manager/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :content, presence: true, length: {minimum: 5}
end

team_task_manager/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  has_many :comments

  has_many :commentors, through: :comments,  :class_name => "User", :foreign_key => :user_id
  has_many :collaborators, through: :tasks,  :class_name => "User", :foreign_key => :user_id

  validates_presence_of :name, :description

  #accepts_nested_attributes_for :tasks

  def tasks_attributes=(tasks_attributes)
    tasks_attributes.values.each do |task_details|
     
      if !task_details["description"] == ""
        self.tasks.find_or_create_by(task_details)
      end
    end
  end

  def self.completed_projects
    # a project is considered complete when all of it's tasks are complete
    # Merge scope
    # tasks.merge(Task.completed)
    where(completed: true)
  end

  def self.incomplete_projects
    where(completed: false)
  end

  def completed_tasks
    tasks.where(completed: true)
  end

  def incomplete_tasks
    tasks.where(completed: false)
  end

end

team_task_manager/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :description, presence: true, length: { minimum: 5 }

  def self.completed
    where(:status => :completed)
  end
end

team_task_manager/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password 
  # before_save :social_login?
  has_many :tasks
  has_many :projects, :through => :tasks
  has_many :comments
  
  validates_presence_of :name, :email
  validates :email, uniqueness: true, length: { minimum: 10}

  # def social_login?
    
  #   if uid
  #     password = "f@c3b00k"
  #   end
  # end

end

team_task_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
    helper_method :current_user

end

team_task_manager/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    # @project = Project.find(params[:project_id]).includes(:comments)
    # @comments = @project.comments # Will not trigger more SQL
    # render :json @comments
  end

  def new
  end

  def create

    @project = Project.find_by(id: params[:comment][:project_id])
    @comment = @project.comments.build(comment_params)
    @comment.user = current_user
    
    if @comment.save
    
      render json: @comment
    else
      render :nothing
    end

    #redirect_to project_path(@project)
  end

  def show
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

team_task_manager/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show
    find_project
    @comment = Comment.new
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @project }
    end
  end

  def new
    @users = User.all
    @project = Project.new
    3.times {@project.tasks.build}
  end

  def create
    
    @project = Project.create(project_params)
    @project.user = current_user
    @project.save
    redirect_to project_path(@project)

  end

  def edit
    find_project
  end

  def update
    find_project
    @project.update(project_params)
    @project.save
    redirect_to project_path(@project)
  end

  def complete
    find_project
    @project.update(completed: true)
    redirect_to root_path
  end

  def destroy
    find_project
    @project.destroy
    redirect_to root_path
  end

  private 
    def project_params
      params.require(:project).permit(:name, :description, :due_date, tasks_attributes: [:description, :user_id])
    end

    def find_project
      @project = Project.find(params[:id])
    end
end

team_task_manager/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    
    if auth.nil?
      @user = User.find_by(email: params[:user][:email])
      if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id 
      redirect_to root_path
      else
      @error = "Invalid Login Please Try Again"
      render :new
      end
   
    else 
      # yours users

      #   id           uid
      #   1            4515


      # facebook users tabe
      #   id
      #   4515

      @user = User.find_or_create_by(facebook_uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
        u.password = SecureRandom.hex
      end
      
      session[:user_id] = @user.id
      redirect_to root_path

    end
  end 



  def destroy
    session.destroy
    redirect_to root_path
  end

  private 
     def auth
      request.env['omniauth.auth']
    end

end

team_task_manager/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @users = User.all
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build
  end

  def create

    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project)
  end

  def show

  end

  def complete
    @task = Task.find_by(id: params[:id])
    @task.update(completed: true)
    
    redirect_to project_path(@task.project)
  end

  private
    def task_params
      params.require(:task).permit(:description, :user_id)
    end
end

team_task_manager/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    respond_to do |f|
      f.html { render :index }
      f.json { render json: @users }
    end
  end
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end


  private 
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

team_task_manager/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @projects = Project.all
    @user = current_user
  end
end

team_task_manager/app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

team_task_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamTaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'error_manifest' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Fuego Task Manager</a>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if current_user.nil? %>
          <li><%= link_to 'Log In', login_path, method: 'get' %></li>
          <li><%= link_to 'Sign Up', signup_path, method: 'get' %></li>
        <% else %>
          <li><%= link_to 'Log Out', logout_path, method: 'post' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>
  
<div class="container">
  <h1></h1>

  
</div>

<div id="footer">
  <div class="container">
    <p class="text-muted">Created by <a href="https://github.com/tuckerbohman5" target="_blank">Tucker Bohman</a></p>
  </div>
</div>



</body>
</html>

team_task_manager/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>

<%= f.label :description %>
<%= f.text_area :description %><br>

<%= f.label "Due Date"%>
<%= f.date_field :due_date %><br>
  
  <ul>
    
    <%= f.fields_for :tasks do |task_form| %>
      
      <li>
        <%= task_form.label "Task" %>
        <%= task_form.text_field :description %>
        <%= task_form.label "User Assigned" %>
        <%= task_form.collection_select :user_id, @users, :id, :name %>
      </li>
        
   
    <% end %>
  </ul>

<%= f.submit %>
<% end %>

team_task_manager/app/views/projects/edit.html.erb
<%=render partial: 'form', locals: {project: @project}%>

team_task_manager/app/views/projects/new.html.erb
<%= render 'form' %>

team_task_manager/app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<h3><%= @project.description %></h3>
<h3>Due Date: <%= @project.due_date %></h3>


<% if !@project.comments.empty? %>
<button id='loadComments'>View Comments</button>
<button hidden="true" id='hideComments'>Hide Comments</button>
<div id="projectComments">


</div>
<% end %>

<%= form_for @comment do |f| %>
<%= f.text_field :content, :placeholder => "New comment" %>
<%= f.hidden_field :project_id, value: @project.id %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.submit "Add comment", id: "addComment" %>
<% end %>


<h5>Tasks:</h5>
<ul>
<h4 style="color:red">Incomplete Tasks</h4>
<% @project.incomplete_tasks.each do |task| %>
  <li><%= task.description %>-<%=task.user.name%><br> <%= link_to "Complete?", task_complete_path(task), method: 'post' %> </li>
<% end %>

<h4 style="color:green">Complete Tasks</h4>
<% @project.completed_tasks.each do |task| %>
  <li><%= task.description %>-<%=task.user.name%></li>
<% end %>
</ul>


<%= link_to "Add Task", new_project_task_path(@project), method: 'get' %><br>

<%= link_to "Edit Project", edit_project_path(@project), method: 'get' %><br>
<%= link_to "Mark as Complete", "/projects/#{@project.id}/complete", method: 'post' if @project.completed == false %><br>

<%= link_to "Delete Project", "/projects/#{@project.id}", method: 'delete' %><br>

team_task_manager/app/views/projects/test.html.erb
<%= form_for @project do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <ul>
    <%= f.fields_for :tasks do |tasks_form| %>
      <li>
        <%= tasks_form.label :description %>
        <%= tasks_form.text_field :description %>
 
      </li>
    <% end %>
  </ul>
<% end %>

team_task_manager/app/views/tasks/_form.html.erb
<%= form_for ([project, task]) do |f| %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.label "Assigned to:" %>
<%= f.collection_select :user_id, @users, :id, :name %>
<%= f.submit "Add Task" %>
<% end %>

team_task_manager/app/views/tasks/new.html.erb
<%=render partial: 'form', locals: {task: @task, project: @project} %>

team_task_manager/app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div id="error_overview">
    <h2>There were errors:</h2>
    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(:user, action: 'signup') do |f| %>
  <% if user.errors[:name].empty? %>
    <div class="field">
  <% else %>
    <div class="field_with_errors">
  <% end %>
      <%= f.label :name %>
      <%= f.text_field :name%><br>
    </div>

  <% if user.errors[:email].empty? %>
    <div class="field">
  <% else %>
    <div class="field_with_errors">
  <% end %>
      <%= f.label :email %>
      <%= f.text_field :email %><br>
    </div>

  <% if user.errors[:password].empty? %>
    <div class="field">
  <% else %>
    <div class="field_with_errors">
  <% end %>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
      <%= f.submit "Sign Up" %>
<%end%>

team_task_manager/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%=render partial: 'form', locals: {user: @user}%>
<%= link_to("Login with Facebook!", "/auth/facebook") %>

team_task_manager/app/views/welcome/home.html.erb
<div class="container">
</div>

  <div class="jumbotron">
    <div class="container">
      <% if session[:user_id].nil? %>
      <%=render partial: 'sessions/form', locals: {user: @user}%>
      <%= link_to("Login with Facebook!", "/auth/facebook") %>
      <% else %>
            <h5 style='color:red'>Logged in as: <%= @user.name if @user.name %></h5>
          <h3 style="color:red">Incomplete Projects:</h3>
            <% Project.incomplete_projects.each do |project| %>
               <h5><%=link_to project.name, project_path(project) %> - Due: <%= project.due_date %></h5><a class="moreInfo" data-id="<%=project.id%>">More info...</a><a  class="hideInfo" data-id="<%=project.id%>">Hide info...</a>
               <p data-id="<%=project.id%>"></p>
            <% end %>
                <%= button_to 'New Project', new_project_path, method: 'get' %>
                <button id="viewUsers">View Users</button>
                <button style="display:none" id="hideUsers">Hide Users</button>
                <div id="users"></div>
          <h3 style="color:green">Completed Projects:</h3>
            <% Project.completed_projects.each do |project| %>
               <h5><%=link_to project.name, project_path(project) %> - Due: <%= project.due_date %></h5>
            <% end %>
      <% end %>
      
      
    </div>
  </div>

team_task_manager/app/views/welcome/old_home.html.erb
<h1>Welcome to Team Task Manager</h1>
  
<% if session[:user_id].nil? %>
   <%=render partial: 'sessions/form', locals: {user: @user}%>
<% else %>
    <h5 style='color:red'>Logged in as: <%= @user.name if @user.name %></h5>
    <h3>Projects:</h3>
    <% @projects.each do |project| %>
      <h5><%=link_to project.name, project_path(project) %> - Due: <%= project.due_date %></h5>
    <% end %>
    <%= button_to 'New Project', new_project_path, method: 'get' %>
<% end %>
<br>
<br>
<%= button_to 'Sign Up', signup_path, method: 'get' %>
<%= button_to 'Log Out', logout_path, method: 'post' %>